### ISSUE TITLE
Crash on cmd autocomplete

### ISSUE THREAD

**Issue by schindlershadow** [Frontrider/thaumic_arcana#63]
Typing / then pressing tab for the autocomplete crashes client.

`Time: 12/4/18 11:31 AM
Description: Updating screen events

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method hu.frontrider.arcana.sided.client.commands.ReloadOffsetsCommand.func_184882_a, parameter server
	at hu.frontrider.arcana.sided.client.commands.ReloadOffsetsCommand.func_184882_a(ReloadOffsetsCommand.kt)
	at net.minecraft.command.CommandHandler.func_180524_a(CommandHandler.java:183)
	at net.minecraftforge.client.ClientCommandHandler.autoComplete(ClientCommandHandler.java:139)
	at net.minecraft.util.TabCompleter.func_186838_a(TabCompleter.java:65)
	at net.minecraft.util.TabCompleter.func_186841_a(TabCompleter.java:47)
	at net.minecraft.client.gui.GuiChat$ChatTabCompleter.func_186841_a(SourceFile:190)
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:70)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`
Thaumic+Arcana-1.1.1
FML: MCP 9.42 Powered by Forge 14.23.5.2795 Optifine OptiFine_1.12.2_HD_U_C7 116 mods loaded, 116 mods active

**Comment by Frontrider** [comment]
I can not reproduce it.

**Comment by Frontrider** [comment]
Try it with a clean installation, it's probably an another mod's doing.

**Comment by Frontrider** [comment]
Can not reproduce, closing.

**Comment by LocalBoomer** [comment]
Same crash just now https://pastebin.com/qc1tx0eb

Was using tab to autocomplete the /reload command (from FTBUtils?)

Okay so ftblib.cfg has an option:
```
   # This will replace /reload with FTB version of it.
    B:replace_reload_command=true
```
I'm guessing this interacting with Thaumic Arcana is causing the issue. Will post a reference there to this report and test with the option disabled to see if that is the problem

**Comment by LocalBoomer** [comment]
Tested with the above setting set to false and no change :/
