### ISSUE TITLE
Trying to maintain the mod

### ISSUE THREAD

**Issue by oliverrook** [Frontrider/thaumic_arcana#85]
Thought this might be the best way to get your attention, couldn't think of any other way, especially since the last time you were on curseforge was in April.
So, I would like to maintain the mod and possibly even expand it, however, I seem to be getting an issue where I'm getting a bunch of errors in Eclipse, specifically about certain classes that don't seem to exist, such as "BlockTaintBase", which doesn't seem to exist in this mod, despite attempting to be imported.
Am I doing something wrong, or missing files?

**Comment by Frontrider** [comment]
Been a while since I touched it but that sounds like a missing thaumcraft dependency.

**Comment by oliverrook** [comment]
I figured it out. Partially.
I didn't have Kotlin plugins
However, now I'm running into an entirely different issue.
I keep getting class not found errors.
I feel like this must be a setup issue.
I'm trying to figure it out on my own, but progress is slow.

Here's an example:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumic Arcana (thaumic_arcana)
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getResourcePath()Ljava/lang/String;
    at hu.frontrider.arcana.items.ItemBase.<init>(ItemBase.kt:19)
    at hu.frontrider.arcana.items.EnchantmentUpgradePowder.<init>(EnchantmentUpgradePowder.kt:30)
    at hu.frontrider.arcana.registrationhandlers.ItemRegistry.<clinit>(ItemRegistry.kt:30)
    at hu.frontrider.arcana.ThaumicArcana.preInit(ThaumicArcana.kt:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at 


One of the first bugs I've been attempting to fix is the crash on startup every time you try to reload a world after opening it once a session. Put in an exception catcher so it'd ignore the error and return a null instead of an outright error.

**Comment by oliverrook** [comment]
Never mind. I was building the .jar file wrong.
I am now in a position to try to fix some of the bugs.

**Comment by oliverrook** [comment]
I have successfully fixed the bug that causes you to crash when you try to rejoin a world by adding in try/catch statements.
Might work on some other bugs now, such as the one keeping the soul capsule from working.

Will post a .jar file containing the two fixes at some point.
Also fixed The Scar code because the github version hasn't been fully updated with that apparently.

Might've figured out how to fix the soul capsule bug where it's not working
I think the required research for a filled soul capsule REQUIRES a filled soul capsule instead of an empty one.
In addition, I noticed that while every other recipe had the aspects all on one line, the one for the filled soul capsule did not.

**Comment by Frontrider** [comment]
@oliverrook If I know your user on curseforge, I'd add you to the project.
I see one `oliverrook` on curseforge, but I want to be sure if that's you.

**Comment by oliverrook** [comment]
That is me, yes.
Also I have indeed figured out how to fix the capsule research.

**Comment by Frontrider** [comment]
I set you up as a maintainer for now, want to see where it goes before I'd hand it over.
